/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2018-10-11 07:22:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class filterOilSample_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("file:/C:/SERVERS/TOMCAT/lib/spring5hibernate5/spring-webmvc-5.0.0.RELEASE.jar", Long.valueOf(1519102724000L));
    _jspx_dependants.put("file:/C:/SERVERS/TOMCAT/lib/spring5hibernate5/spring-security-taglibs-5.0.0.RELEASE.jar", Long.valueOf(1514528160000L));
    _jspx_dependants.put("/WEB-INF/views/locationFilterView.jsp", Long.valueOf(1539241803000L));
    _jspx_dependants.put("file:/C:/SERVERS/TOMCAT/lib/spring5hibernate5/jstl-impl-1.2.jar", Long.valueOf(1519102722000L));
    _jspx_dependants.put("jar:file:/C:/SERVERS/TOMCAT/lib/spring5hibernate5/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308107170000L));
    _jspx_dependants.put("jar:file:/C:/SERVERS/TOMCAT/lib/spring5hibernate5/spring-security-taglibs-5.0.0.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1511793172000L));
    _jspx_dependants.put("jar:file:/C:/SERVERS/TOMCAT/lib/spring5hibernate5/spring-webmvc-5.0.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1506576796000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction applyFilters() {\n");
      out.write("\t\t$('body').css('display', 'none');\n");
      out.write("\t\t\n");
      out.write("\t\t//\tvar filterModel = {};\n");
      out.write("\t\t//filterModel.selectedCircle =[{circleCode: $(\"#circleDD\").val()}];\n");
      out.write("\t\t//filterModel.selectedCircle = $(\"#circleDD\").val();\n");
      out.write("\t\t//filterModel.selectedDivision = $(\"#divisionDD\").val();\n");
      out.write("\t\t//filterModel.selectedSubstation = $(\"#substationDD\").val();\n");
      out.write("\n");
      out.write("\t\tvar circleSelected = $(\"#circleDD\").val();\n");
      out.write("\t\tvar divisionSelected = $(\"#divisionDD\").val();\n");
      out.write("\t\tvar substationSelected = $(\"#substationDD\").val();\n");
      out.write("\t\tvar bottleNo = $(\"#bottleNo\").val();\n");
      out.write("\t\tvar sampleNo = $(\"#sampleNo\").val();\n");
      out.write("\t\tvar referenceMemoDate = $(\"#referenceMemoDate\").val();\n");
      out.write("\t\tvar referenceMemoNo = $(\"#referenceMemoNo\").val();\n");
      out.write("\n");
      out.write("\t\t// \t\t$.post(\"/ODTL/filterEquipmentOBJ\",{filterModel1:filterModel},populateTableContainer)\n");
      out.write("\t\t// \t\t\t\t.done(function() {})\n");
      out.write("\t\t// \t\t\t\t.fail(function(data, status, er) {alert(\"Couldn't load location information !\" + data + er);});\n");
      out.write("\t\t// \t\t\t}\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : \"/ODTL/filterOilSample\",\n");
      out.write("\t\t\ttype : \"POST\",\n");
      out.write("\t\t\tdata : {\n");
      out.write("\t\t\t\tcircleSelected : circleSelected,\n");
      out.write("\t\t\t\tdivisionSelected : divisionSelected,\n");
      out.write("\t\t\t\tsubstationSelected : substationSelected,\n");
      out.write("\t\t\t\tbottleNo : bottleNo,\n");
      out.write("\t\t\t\tsampleNo : sampleNo,\n");
      out.write("\t\t\t\treferenceMemoDate : referenceMemoDate,\n");
      out.write("\t\t\t\treferenceMemoNo : referenceMemoNo\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess : function(response) {\n");
      out.write("\t\t\t\t$(\"#tableContainer\").replaceWith(response);\n");
      out.write("\t\t\t\t$('body').css('display', 'block');\n");
      out.write("\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror : function(data, status, er) {\n");
      out.write("\t\t\t\talert(\"Error\" + data + er);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t// \t\t$.ajax({\n");
      out.write("\t\t// \t\t\turl : \"/ODTL/filterEquipmentOBJ\",\n");
      out.write("\t\t// \t\t\ttype : \"POST\",\n");
      out.write("\t\t// \t\t\tcontentType : \"application/json\",\n");
      out.write("\t\t// \t\t\tdata : JSON.stringify({\n");
      out.write("\t\t// \t\t\t\tfilterModel : filterModel\n");
      out.write("\t\t// \t\t\t}),\n");
      out.write("\t\t// \t\t\tsuccess : function(response) {\n");
      out.write("\t\t// \t\t\t\t$(\"#tableContainer\").replaceWith(response);\n");
      out.write("\t\t// \t\t\t},\n");
      out.write("\t\t// \t\t\terror : function(data, status, er) {\n");
      out.write("\t\t// \t\t\t\talert(\"Error\" + data + er);\n");
      out.write("\t\t// \t\t\t}\n");
      out.write("\t\t// \t\t});\n");
      out.write("\n");
      out.write("\t\t//).fail(function(data, status, er) {alert(\"Couldn't load location information !\" + data + er);}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction populateTableContainer(data, status) {\n");
      out.write("\t\t$(\"#tableContainer\").replaceWith(data);\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("\t$(document)\n");
      out.write("\t\t\t.ready(\n");
      out.write("\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t$(\"#filter-panel\")\n");
      out.write("\t\t\t\t\t\t\t\t.on(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"hide.bs.collapse\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#btn1\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.html(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t' <i class=\"fa fa-filter\" style=\"font-size: 18px\"> </i> Filter');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t$(\"#filter-panel\")\n");
      out.write("\t\t\t\t\t\t\t\t.on(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"show.bs.collapse\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#btn1\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.html(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t' <i class=\"fa fa-window-close\"></i> </i> Close');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<button id=\"btn1\" type=\"button\" class=\"btn btn-light btn-sm float-right\"\n");
      out.write("\tdata-toggle=\"collapse\" data-target=\"#filter-panel\">\n");
      out.write("\t<i class='fa fa-filter' style='font-size: 18px'> Filter </i>\n");
      out.write("</button>\n");
      out.write("<div class=\"card card-default\">\n");
      out.write("\n");
      out.write("\t<div class=\"card-body\">\n");
      out.write("\t\t<div class=\"filter-panel\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"filter-panel\" class=\"collapse  border-secondary\">\n");
      out.write("\t\t\t\t<form class=\"form-inline\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\tfunction submitform() {\n");
      out.write("\t\t\t$('#circleDD').find('option').remove().end();\n");
      out.write("\t\t\t$('#divisionDD').find('option').remove().end();\n");
      out.write("\t\t\t$('#substationDD').find('option').remove().end();\n");
      out.write("\t\t\t$.post(\"/ODTL/getLocationsModel\", {\n");
      out.write("\t\t\t\tcircleSelected : $(\"#circleDD\").val(),\n");
      out.write("\t\t\t\tdivisionSelected : $(\"#divisionDD\").val(),\n");
      out.write("\t\t\t\tsubstationSelected : $(\"#substationDD\").val()\n");
      out.write("\t\t\t}, populate).done(function() {\n");
      out.write("\t\t\t\t//alert( \"Employee Added\" );\n");
      out.write("\t\t\t}).fail(function(data, status, er) {\n");
      out.write("\t\t\t\talert(\"Couldn't load location information !\" + data + er);\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\tfunction addEmpty()\n");
      out.write("\t\t{\n");
      out.write("\t\t\taddEmptyCircle();\n");
      out.write("\t\t\taddEmptyDivision();\n");
      out.write("\t\t\taddEmptySubstation();\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction addEmptyCircle()\n");
      out.write("\t\t{\n");
      out.write("\t\t$('#circleDD').append(\n");
      out.write("\t\t\t\t$(\"<option></option>\").attr(\"value\", \"\")\n");
      out.write("\t\t\t\t\t\t.text(\"Select Circle\"));\n");
      out.write("\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction addEmptyDivision()\n");
      out.write("\t\t{\n");
      out.write("\t\t\n");
      out.write("\t\t$('#divisionDD').append(\n");
      out.write("\t\t\t\t$(\"<option></option>\").attr(\"value\", \"\")\n");
      out.write("\t\t\t\t\t\t.text(\"Select Division\"));\n");
      out.write("\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction addEmptySubstation()\n");
      out.write("\t\t{\n");
      out.write("\t\t\n");
      out.write("\t\t$('#substationDD').append(\n");
      out.write("\t\t\t\t$(\"<option></option>\")\n");
      out.write("\t\t\t\t\t\t.attr(\"value\", \"\").text(\n");
      out.write("\t\t\t\t\t\t\t\t\"Select Sub-Station\"));\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction populate(data, status) {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\taddEmpty();\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t$.each(data.circleList, function(idx, obj) {\n");
      out.write("\t\t\t\t//alert(obj.circleDescription);\n");
      out.write("\t\t\t\t$('#circleDD').append(\n");
      out.write("\t\t\t\t\t\t$(\"<option></option>\").attr(\"value\", obj.circleCode)\n");
      out.write("\t\t\t\t\t\t\t\t.text(obj.circleDescription));\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$.each(data.divisionList, function(idx, obj) {\n");
      out.write("\t\t\t\t//alert(obj.divisionDescription);\n");
      out.write("\t\t\t\t$('#divisionDD').append(\n");
      out.write("\t\t\t\t\t\t$(\"<option></option>\").attr(\"value\", obj.divisionCode)\n");
      out.write("\t\t\t\t\t\t\t\t.text(obj.divisionDescription));\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$.each(data.substationList, function(idx, obj) {\n");
      out.write("\t\t\t\t//alert(obj.substationDescription);\n");
      out.write("\t\t\t\t$('#substationDD').append(\n");
      out.write("\t\t\t\t\t\t$(\"<option></option>\")\n");
      out.write("\t\t\t\t\t\t\t\t.attr(\"value\", obj.substationCode).text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tobj.substationDescription));\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction submitCircle() {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$('#divisionDD').find('option').remove().end();\n");
      out.write("\t\t\t$('#substationDD').find('option').remove().end();\n");
      out.write("\t\t\t$.post(\"/ODTL/getLocationsModel\", {\n");
      out.write("\t\t\t\tcircleSelected : $(\"#circleDD\").val(),\n");
      out.write("\t\t\t\tdivisionSelected : null,\n");
      out.write("\t\t\t\tsubstationSelected : null\n");
      out.write("\t\t\t}, circleSelected).done(function() {\n");
      out.write("\t\t\t\t//alert( \"Employee Added\" );\n");
      out.write("\t\t\t}).fail(function(data, status, er) {\n");
      out.write("\t\t\t\talert(\"Couldn't load location information !\" + data + er);\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction circleSelected(data, status) {\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\taddEmptyDivision();\n");
      out.write("\t\t\taddEmptySubstation();\n");
      out.write("\t\t\t$.each(data.divisionList, function(idx, obj) {\n");
      out.write("\t\t\t\t//alert(obj.divisionDescription);\n");
      out.write("\t\t\t\t$('#divisionDD').append(\n");
      out.write("\t\t\t\t\t\t$(\"<option></option>\").attr(\"value\", obj.divisionCode)\n");
      out.write("\t\t\t\t\t\t\t\t.text(obj.divisionDescription));\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$.each(data.substationList, function(idx, obj) {\n");
      out.write("\t\t\t\t//alert(obj.substationDescription);\n");
      out.write("\t\t\t\t$('#substationDD').append(\n");
      out.write("\t\t\t\t\t\t$(\"<option></option>\")\n");
      out.write("\t\t\t\t\t\t\t\t.attr(\"value\", obj.substationCode).text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tobj.substationDescription));\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction submitDivision() {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$('#substationDD').find('option').remove().end();\n");
      out.write("\t\t\t$.post(\"/ODTL/getLocationsModel\", {\n");
      out.write("\t\t\t\tcircleSelected : $(\"#circleDD\").val(),\n");
      out.write("\t\t\t\tdivisionSelected : $(\"#divisionDD\").val(),\n");
      out.write("\t\t\t\tsubstationSelected : null\n");
      out.write("\t\t\t}, divSelected).done(function() {\n");
      out.write("\t\t\t\t//alert( \"Employee Added\" );\n");
      out.write("\t\t\t}).fail(function(data, status, er) {\n");
      out.write("\t\t\t\talert(\"Couldn't load location information !\" + data + er);\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction divSelected(data, status) {\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\taddEmptySubstation();\n");
      out.write("\t\t\t$.each(data.substationList, function(idx, obj) {\n");
      out.write("\t\t\t\t//alert(obj.substationDescription);\n");
      out.write("\t\t\t\t$('#substationDD').append(\n");
      out.write("\t\t\t\t\t\t$(\"<option></option>\")\n");
      out.write("\t\t\t\t\t\t\t\t.attr(\"value\", obj.substationCode).text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tobj.substationDescription));\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction submitSS() {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$.post(\"/ODTL/getLocationsModel\", {\n");
      out.write("\t\t\t\tcircleSelected : $(\"#circleDD\").val(),\n");
      out.write("\t\t\t\tdivisionSelected : $(\"#divisionDD\").val(),\n");
      out.write("\t\t\t\tsubstationSelected : $(\"#substationDD\").val()\n");
      out.write("\t\t\t}, ssSelected).done(function() {\n");
      out.write("\t\t\t\t//alert( \"Employee Added\" );\n");
      out.write("\t\t\t}).fail(function(data, status, er) {\n");
      out.write("\t\t\t\talert(\"Couldn't load location information !\" + data + er);\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction ssSelected(data, status) {\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("<script>\n");
      out.write("\t\t$(document).ready(function() {\n");
      out.write("\t\t\tsubmitform();\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"form-control col-md-4\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\tCircle <select id=\"circleDD\" class=\"form-control input-sm\"\n");
      out.write("\t\tonchange=\"submitCircle()\">\n");
      out.write("\n");
      out.write("\t</select>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"form-control col-md-4\">\n");
      out.write("\n");
      out.write("\tDivision <select id=\"divisionDD\" class=\"form-control input-sm\"\n");
      out.write("\t\tonchange=\"submitDivision()\">\n");
      out.write("\t</select>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"form-control col-md-4\">\n");
      out.write("\n");
      out.write("\tSubstation <select id=\"substationDD\" class=\"form-control input-sm\"\n");
      out.write("\t\tonchange=\"submitSS()\">\n");
      out.write("\t</select>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\tReference Memo No<input type=\"text\" id=\"referenceMemoNo\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"referenceMemoNo\" class=\"form-control input-sm\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-control\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\tReference Memo Date <input type=\"text\" class=\"date-picker\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"referenceMemoDate\" class=\"form-control input-sm\" />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-control\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\tSample No <input type=\"text\" id=\"sampleNo\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control input-sm\" />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-control\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\tBottle No <input type=\"text\" id=\"bottleNo\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control input-sm\" />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"row  float-right\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"button\" onclick=\"applyFilters()\" value=\"Apply Filters\"\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-sm\" /> <a\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-light btn-sm float-right\"\n");
      out.write("\t\t\t\t\t\thref=\"javascript:window.location='equipmentListNew'\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-plus\"></span>Clear Filters</a>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
